### ISSUE TITLE
Update and push to home assistant?

### ISSUE THREAD

**Issue by dshokouhi** [sogood007/home-assistant-obihai#1]
Hi I found your custom component but had to make a few changes for it to work with the latest HA updates.  Were you planning to add this as an official component? Are you still using this integration?

**Comment by sogood007** [comment]
I haven't used this for a while.  Please feel free to use it and it will be great if you can help add as an official component

**Comment by sogood007** [comment]
Thanks @dshokouhi Look like this is already in HA.
